//
//  Viking.swift
//  AZTabBarController
//
//  Created by Yannick Edouard MEKONGO ABANDA on 06/02/2023.
//

import Foundation
import UIKit
import SwiftUI

struct Viking : Identifiable {
    var id =  UUID()
    var name : String
    var imageUrl : String
    var desc: String
}

class Datas {
    
    func vikings() -> [Viking] {
    return [
    Viking(name: "Roi Aelle", imageUrl: "aelle", desc: "Le Roi Aelle règne sur la Northumbrie, un royaume d'Angleterre.\nSes terres sont les premières touchées par les raids vikings organisés par Ragnar Lothbrok. Il doit alors faire face à une nouvelle menace qu'il n'a pas l'habitude de traiter.\nC'est un homme autoritaire qui ne tolère pas l'échec et un bon vivant, appréciant la bonne chair et l'alcool ce qui se reflète sur son tour de taille. Sur les champs de batailles, il préfère rester à distance des combats, observant. S'il n'est pas le plus rusé, il reste avisé et il sait quand une offre peut lui être profitable et où doit se situer les limites de sa confiance.\nIl n'a pas de respect pour les païens. "),
    Viking(name: "Aslaug", imageUrl: "aslaug", desc: "Aslaug est la fille de Brynnhildur, la légendaire guerrière au bouclier, et de Sigurd, un héros des sagas nordiques qui tua le dragon Fafnir. Ils sont décédés avant qu'elle puisse les connaître.\nElle rencontre Ragnar lors de sa visite dans le Götaland. Des hommes à lui l'ont espionné, ainsi que ses guerrières au bouclier, alors qu'elles se baignaient. Elle demande donc réparation à leur chef et elle fait ainsi la rencontre de Ragnar dont elle devient l'amante puis l'épouse.\nAu fil du temps, la rancoeur et la déception s'installent en elle face à l'échec de son mariage et à son incapacité à obtenir l'amour de Ragnar. Elle est également jalouse de Lagertha qu'elle ne pense jamais pouvoir égaler.\nCependant, Aslaug donne quand même naissance aux fils promis par le Voyant à Ragnar. Si elle se montre être une mère concernée et soucieuse de ses enfants, elle les oublie parfois au profit de ses propres chagrins, ce qui est cause de tragédie. Elle a également une préférence pour Ivar, son enfant handicapé, à qui elle passe tous les caprices.\nEn l'absence de son époux, Aslaug dirige Kattagat qui se développe en un port de commerce prospère. Cela l'amène à devenir ambitieuse et vouloir changer sa position. Sans compter qu'elle ne partage pas les vues de Ragnar à propos du Christianisme, c'est une fervente adepte de leur religion. Sous une apparence d'innocence et d'indifférence, elle est davantage perspicace qu'elle ne le montre.\nC'est aussi une völva, elle peut voir l'avenir sous forme de rêves ou de prophéties."),
    Viking(name: "Athelstan", imageUrl: "athelstan", desc: "Athelstan est un moine appartenant au monastère de Lindisfarne, dans lequel il a été placé enfant. En effet, ses parents avaient déjà une progéniture nombreuse et ne pouvaient pas se permettre de l'entretenir.\nSon monastère est attaqué lors d'un raid viking et il est capturé. Il a la vie sauve grâce à Ragnar, impressionné par le fait qu'il parle leur langue.\nCe dernier choisit d'en faire son esclave et de glaner des informations sur les terres saxonnes. Au fil du temps, un lien profond se noue entre les deux hommes, devenant amis et confidents, et il s'intègre à la société viking.\nEt en dépit d'avoir le choix de rester en Wessex, un choix sécuritaire et qui lui apporterait beaucoup, il reste à Kattegat car son avenir est avec Ragnar. Leur prochain projet étant déjà en route : un raid sur la magnifique cité de Paris qu'il a jadis visité.\nAthelstan est cultivé, intelligent mais innocent dans ses relations avec autrui. Curieux et avide de connaissances, il a beaucoup voyagé ce qui lui a permit d'apprendre de nouveaux langages et de découvrir d'autres cultures. Il apprécie également l'art sous toutes ses formes et il est lui-même un artiste qui peint de magnifiques enluminures.\nIl devient par la suite un bon guerrier grâce à son apprentissage auprès de Torstein et de Ragnar et participe même aux raids.\nPieux, Athelstan est déchiré entre sa croyance en Dieu et ses croyances païennes. Cela lui vaut à maintes reprises d'être accusé d'hérésie et de manquer de loyauté par ses ennemis qu'ils soient saxons ou vikings."),
    Viking(name: "Bjorn Lothbrok", imageUrl: "bjorn", desc: "Björn est le fils de Ragnar et de Lagertha, ainsi que l'héritier de Kattegat et le troisième époux de Torvi.\nL'âge de douze ans dans la société viking est un moment important pour un jeune homme et il reçoit des mains du Jarl Haraldson, son bracelet de bras.\nCependant, il reste trop jeune pour participer aux raids et doit rester à la maison en compagnie de sa soeur et sous la surveillance d'Athelstan.\nSes parents se séparent à un moment et il quitte son père afin de rester avec Lagertha. Ces années seul auprès de sa mère leur permettent de construire une relation forte et Björn est particulièrement protecteur d'elle.\nCeci-dit il ne porte pas de griefs envers ses frères, issu du second mariage de son père, et ils s'entendent bien en général.\nQuant à Ragnar, beaucoup de temps va s'écouler avant qu'ils ne se revoient et participants ensemble aux raids, ses premiers, ils renouent petit à petit entre eux. Peu importe les choix de son père, qu'ils soient d'accord ou non, il le soutient et lui est loyal. Il en profite également pour apprendre de sa sagesse.\nBjörn a été éduqué dans la pure tradition nordique et il souhaite plus que tout faire ses preuves au combat, devenir une personne reconnue pour ses propres mérites. Sa jeunesse et sa fougue lui font manquer la vue à long terme. Il doit encore apprendre la patience et la réflexion mais il est intelligent et attentif.\n De Ragnar, il a hérité du goût pour l'exploration, ainsi que de la curiosité envers les autres cultures, et découvrir les secrets de la Méditerranée et de ses terre est un de ses principaux objectifs."),
    Viking(name: "Roi Ecbert", imageUrl: "ecbert", desc: "Le roi Ecbert est le roi du Wessex, un des royaumes qui compose l'Angleterre de l'époque, et le père d'Aethelwulf. Il a été éduqué à la cour du roi Charlemagne.\nÀ l'instar du Roi Aelle, il doit faire face aux raids vikings sur ses terres mais sa manière de régler le problème ainsi que ses liens avec Ragnar sont différents.\nLes deux hommes nouent des liens d'amitié en dépit de leur adversité et ont un grand respect l'un pour l'autre. il faut dire que les deux hommes se ressemblent beaucoup. Ils partagent également un intérêt commun pour Athelstan.\nEcbert est intelligent, rusé, ambitieux et calculateur et il cache ses traits de personnalité sous un personnage amical et digne de confiance. Cela le rend d'autant plus dangereux, surtout qu'il est prêt à sacrifier ses proches, et les autres, sur l'autel de ses ambitions.\nLe massacre de la colonie viking, la trahison de Kwenthrith ou l'adoption d'Alfred par Aethelwulf, issu de l'adultère de sa femme, et les humiliations qui s'en suivent en sont de bons exemples.\nSon attitude et ses choix ont fait de lui un excellent roi, reconnu par tous, qui a su apporter la prospérité, la grandeur et la force à son royaume. Il annexe d'ailleurs par la suite la Mercie, en pleine querelle de succession, seulement par sa propre réputation.\nCependant, il montre un sincère attachement et de la gentillesse pour Athelstan. Cette affection se reportera sur son fils, Alfred. Il devint également plus aimable et doux avec Judith, sa belle-fille. Et malgré son attitude, il aime réellement son fils, Aethelwulf.\nEcbert est fasciné par les cultures païennes comme celles des romains et des vikings. Sa compréhension des différentes civilisations et son ouverture d'esprit lui sont de précieux atouts, qui lui permettent d'acquérir de nouvelles connaissances afin de gérer à son avantage les diverses situations qui se présentent à lui.\nCela n'est pas du goût de son entourage, dévot et croyant. Lui ne voit en la religion qu'un outil, pas si différent des autres, qu'il peut utiliser à son avantage dans ses projets."),
    Viking(name: "Floki", imageUrl: "floki", desc: "Floki, l'époux de Helga, est un constructeur de bateau talentueux, et en général un charpentier de génie, et le meilleur ami de Ragnar.\nIl construit pour ce dernier un nouveau modèle de bateau qui puisse naviguer longtemps en haute mer et qui soit davantage rapide et adapté à des raids. Il participe aux premières expéditions en Angleterre.\nC'est un homme excentrique, bizarre et loufoque qui cache une personnalité plus troublé et fragile. Il est également un homme dévoué, d'une grande fidélité et loyauté, reconnu parmi ses pairs pour sa sagesse et son intelligence.\nMais ce qu'il est le plus remarquable chez Floki, est sa profonde et inaltérable croyance dans le religion nordique, dont il en est un ardent défenseur.\nD'ailleurs c'est l'un des principaux points qui l'oppose à Athelstan car il voit sa religion comme une menace pour la sienne. Leur affection pour Ragnar, en étant un autre.\nCette rivalité finit par l'emmener dans un endroit sombre que même Helga ne peut supporter et qui lui aliène l'amitié de Ragnar. Les pertes de sa fille puis de sa femme contribuent à sa désespérance et il part dans un voyage sans retour au premier abord mais qui lui permet de faire une incroyable découverte : l'Islande.\nEn combat, il a développé ses propres techniques afin de compenser sa frêle stature et il utilise une petite hache et un long couteau au lieu des traditionnelles grandes haches et lances. "),
    Viking(name: "Jarl Haraldson", imageUrl: "haraldson", desc: "Le Jarl Haraldson est le dirigeant de Kattegat et l'époux de Siggy.\nIl est chargé en tant que Jarl de présider la cérémonie des bracelets de passage à l'âge adulte - et par extension de serment d'allégeance - à laquelle participe Björn. Il se retrouve rapidement confronté à son père, Ragnar, qui ne partage pas sa politique.\nC'est un puissant et audacieux guerrier, qui s'est forgé une réputation dans sa jeunesse en participant à des raids dans l'Est. Cela lui valut d'accéder au rang de Jarl. Il est profondément amoureux de sa femme et très attaché à ses enfants.\nMalheureusement la mort de ses deux fils, assassinés, changea sa personnalité et en fit un homme colérique, dur et méfiant. Inquiet, le Jarl cherche par tout les moyens à garder son pouvoir et sa position, quitte à prendre des décisions douteuses.\nCeci-dit, cet événement n'est pas uniquement responsable de son comportement actuel, il montre clairement que pour servir ses ambitions et ses intérêts, qu'il n'est pas très regardant sur les actes à commettre."),
    Viking(name: "Roi Horik", imageUrl: "horik", desc: "Le roi Horik est le souverain du Danemark, ainsi que l'époux de Gunnhild et le père d'Erlendur et d'Ari.\nIl rencontre Ragnar pour la première fois au Temple d'Upsala. Il lui demande un service, celui de l'aider à régler un différent foncier avec le Jarl Borg.\nIl se démarque rapidement comme étant un maître manipulateur qui n'hésite pas à mentir dans ses propres intérêts. Il est autoritaire et exige une loyauté et une obéissance sans faille de ses sujets.\nDe plus, au contraire de Ragnar qui se montre visionnaire dans ses désirs pour son peuple et ses méthodes, il reste un homme de son époque, avec une vision limitée des événements.\nSur les champs de bataille, il se révèle être un féroce guerrier qui se lance au coeur de la mêlée. Du côté de ses croyances, il est un adepte fervent de la religion nordique et déteste particulièrement les chrétiens.\nOn peut apercevoir un aspect plus doux de sa personnalité lorsqu'il est avec ses fils."),
    Viking(name: "Jarl Borg", imageUrl: "jarl borg", desc: "Le Jarl Borg est un chef important, résidant au Götaland.\nIl est en litige avec le Roi Horik au sujet de terres qu'ils considèrent comme siennes. Ragnar est envoyé par le Roi Horik, dont le Jarl Borg ne reconnait pas l'autorité, afin de résoudre le problème.\nC'est un homme rusé, féroce et déterminé. En combat, il reste derrière le mur de bouclier et tue ceux qui ont le malheur de passer le mur. Observateur, il est un habile stratège sur le champ de bataille et il réfléchit soigneusement ses décisions. "),
    Viking(name: "Lagertha Lothbrok", imageUrl: "lagertha", desc: "Lagertha est une fille de fermiers, élevée en tant que skjaldmö (guerrière au bouclier). Elle est la première épouse de Ragnar Lothbrok et la mère de ses premiers enfants dont Björn, son aîné et successeur.\nPendant que son époux, en compagnie de ses hommes, part à l'Ouest découvrir de nouvelles terres, elle reste à la maison s'occuper de leurs enfants et de leur ferme, en dépit de ses protestations.\nElle arrive quand même à participer à la seconde expédition.\nIl faut dire qu'elle n'est pas seulement une mère et une femme au foyer, attentionnée, douce et compatissante. C'est aussi une femme forte, fière et indépendante ainsi qu'une guerrière douée, parfois brutale, Elle partage d'ailleurs le goût de l'aventure de son mari.\nPetit à petit, avec persévérance et habileté, Lagertha grimpe l'échelle du pouvoir par elle-même et obtient également vengeance sur les personnes qui la trahissent. Elle est appréciée par son peuple et ses gens et se montre sage et intelligente dans ses décisions. Mais son orgueil peut lui jouer des tours.\nElle ne remet pas non plus en question les prophéties du Voyant faite à son égard. Si c'est la volonté des Dieux, alors cela en sera ainsi."),
    Viking(name: "Ragnar Lothbrok", imageUrl: "ragnar", desc: "Ragnar Lothbrok est un fermier et un viking qui pense être destiné à un grand avenir. Insatisfait par la politique de son Jarl, lassé de piller les terres de l'est, vide de toutes richesses et de défis, il décide de mener une expédition secrète vers les terres de l'Ouest. Pour ce fait, il demande à son meilleur ami Floki de construire un nouveau type de bateau.\nPar la suite, il devient le jarl de Kattegat puis son roi en défaisant ses ennemis mais l'exploration reste son principal rêve. Il part donc à la conquête de la Francie Occidentale, tout en tentant d'installer des colons dans le Wessex.\nEn dépit de ses succès, sa vie est marquée par des tragédies et des difficultés dans ses relations. Rapidement, il est clair qu'il n'a pas tout à fait la vie qu'il désirait alors.\nRagnar est un redoutable guerrier, né pour le combat. Il est ambitieux, audacieux, assoiffé de gloire et de reconnaissance mais également de connaissances. Cependant ce qui le distingue des autres guerriers, c'est son intelligence et sa clairvoyance. Il a une vision sur le long terme et comprend rapidement les enjeux qui se posent, aussi bien pour lui que pour son peuple.\nIl est curieux et fait preuve d'ouverture d'esprit envers les autres religions et cultures. Ses connaissances ne lui servent pas que dans un but stratégique, il est vraiment intéressé. Cela se démontre particulièrement lors de ses interactions avec Athelstan.\nHomme pieux, Ragnar possède une foi inébranlable dans ses dieux, se réclamant particulièrement d'Odin, et porte un grand respect aux traditions. La volonté des dieux le guide dans ses actes et ses décisions. Son érudition dans ce domaine est conséquente et il se rappelle des petits détails des légendes.\nIl respecte le courage et ses adversaires ainsi que sa parole ce qui peut parfois le mettre dans des situations inconfortables.\nEn dehors de son aspect viking, c'est un homme attaché, dévoué et protecteur à sa famille et ses amis, qui peut être aveuglé par son amour pour eux. Son attachement à ses proches peut le mener à des extrémités particulièrement violentes lorsque ceux-ci sont blessés ou pire.\nRagnar se montre difficile d'accès pour son entourage car il est taciturne, secret, gardant ses pensées et ses projets pour lui et lorsqu'il se révéle, il démontre bien souvent qu'il a une longueur d'avance. Cela empoisonne ses relations avec eux.\nIl sait également qu'il est un homme moins bon qu'il le ne voudrait."),
    Viking(name: "Rollo Lothbrok", imageUrl: "rollo", desc: "Rollo est le frère aîné de Ragnar Lothbrok.\nIl accompagne son frère dans les premières expéditions à l'Ouest et le suit dans ses aventures. Sa jalousie envers lui et son désir envers Lagertha ont mis à rude épreuve leur relation et l'entraîna dans des situations troubles et lourdes de conséquences.\nDe prime abord, il apparaît sauvage, impulsif, hédoniste et agressif mais il est également émotionnel, fragile, ce qui permet à plusieurs personnes de le manipuler et de se servir de ses failles. Son insatisfaction, son sentiment d'insuffisance et son ressentiment vis-à-vis de son frère l'empêchent d'évoluer et de mûrir.\nAvec les années et les épreuves, il devient une personne plus sage et réfléchie dont ne peut mettre en doute la loyauté et la fidélité. De plus, il arrive finalement à trouver sa place dans un lieu inattendu, lui permettant de s'épanouir.\nEn réalité, il cherchait simplement un endroit, celui où il pourrait être aimé et sortir de l'ombre de son frère. Devenir Duc et gendre de l'Empereur Charles lui vaut peut-être l'inimitié de son peuple mais il a enfin un lieu où ses propres ambitions peuvent fleurir.\nEn combat, c'est un guerrier puissant, féroce, redoutable et le premier à se jeter dans la bataille. Il n'a aucune pitié pour ses adversaires. Sa force lui permet de réaliser de nombreux exploits. Il sait également jauger la situation sur un champ de bataille et savoir qui des forces en présence va l'emporter. Il est considéré comme l'un des meilleurs guerriers de Kattegat.\nIl est probablement ambidextre vu qu'il peut lancer des armes de jet avec efficacité des deux mains."),
    Viking(name: "Siggy Haraldson", imageUrl: "siggy", desc: "Siggy est l'épouse du Jarl Haraldson et la mère de Thyri.\nDurant le règne de son époux, elle est une femme admirée qui remplit ses fonctions d'épouse du Jarl avec efficacité et qui jouit de son statut.\nNéanmoins, ses sentiments naissants pour Rollo et surtout les décisions que prennent Haraldson à propos de leur fille, affectent son ressentiment à son égard et ses actions futures.\nElle est avant tout une survivante dont la loyauté évolue en fonction des événements. Elle manipule et ment afin de gagner des avantages ce qui n'empêchent pas ses affections d'être sincères et d'être une personne dévouée.\nIl faut dire que sa vie a été marquée par bien des tragédies. Avant le décès de son mari et la perte de son statut dans la socièté - ce qui se traduit par une vie précaire et un sentiment d'insécurité - ses deux fils ont été brutalement assassinés.\nElle est d'ailleurs une bonne mère, responsable et aimant les enfants.")
    ]
    }
}
